version: '3'

networks:
  backend:

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yii2
      MYSQL_USER: yii2
      MYSQL_PASSWORD: password
    ports:
      - '4307:3306'
    networks:
      - backend

  nginx:
    build:
      context: .docker/nginx
    volumes:
      - './code:/var/www/html'
    restart: always
    ports:
      - "7777:80"
      - "443:443"
    depends_on:
      - php-fpm
    networks:
      - backend

  php-fpm:
    build:
      context: .docker/php-fpm
    volumes:
      - './code:/var/www/html'
      - './.docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
      - './.docker/php-fpm/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini'
    restart: always
    ports:
      - 9000:9000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend

volumes:
  code:
